---

- name: Check current Docker Compose version
  command: docker-compose --version
  register: docker_compose_current_version
  changed_when: false
  failed_when: false

- name: Delete existing Docker Compose if it is outdated
  file:
    path: "{{ docker_compose_path }}"
    state: absent
  when:
    - docker_compose_current_version.stdout is defined
    - docker_compose_version not in docker_compose_current_version.stdout

- name: Install Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}
    dest: "{{ docker_compose_path }}"
    mode: 0755
