---

- import_tasks: setup.yml

- name: Ensure that Docker is installed
  package: name={{ docker_package }} state={{ docker_package_state }}

- import_tasks: configure.yml

- name: Ensure that Docker is started and enabled
  service: name=docker state=started enabled=yes

- include_tasks: docker-compose.yml
  when: docker_install_compose
