---

- name: Ensure that old versions of Docker are not installed
  package:
    name: "{{ item }}"
    state: absent
  with_items:
    - docker
    - docker-engine
    - docker.io

- name: Ensure that dependencies are installed.
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: Add Docker’s official GPG key
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  register: repo_key_added
  ignore_errors: yes

- name: Add Docker APT repository
  apt_repository:
    repo: "{{ item }}"
    state: present
    filename: docker
    update_cache: no
  with_items: "{{ docker_apt_repository }}"

- name: Update APT cache
  apt: update_cache=yes
  changed_when: no
