---

- name: Ensure that old versions of Docker are not installed
  package:
    name:
      - docker
      - docker-engine
      - docker.io
    state: absent

- name: Ensure that dependencies are installed.
  package:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present

# Deprecation of ‘apt-key’
# - name: Add Docker’s official GPG key
#   apt_key:
#     id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
#     url: https://download.docker.com/linux/ubuntu/gpg
#     state: present
#   register: add_repo_key
#   ignore_errors: yes

- name: Add Docker’s official GPG key
  get_url:
    url: "{{ docker_gpg_key_url }}"
    dest: "{{ docker_gpg_key_dest }}"
    checksum: "{{ docker_gpg_key_checksum }}"
  register: add_repo_key
  ignore_errors: "{{ ansible_check_mode }}"

- name: Add Docker APT repository
  apt_repository:
    repo: "{{ item }}"
    state: present
    filename: docker
    update_cache: no
  with_items: "{{ docker_apt_repository }}"
  notify: update apt cache

- meta: flush_handlers
